#!/bin/bash
#   
# kasutajate lisamise skript

if [ $# -ne 1 ]; then
    echo "Help: $0 failinimi"	
else
  failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "Fail on korras"
    for nimi in $(cat $failinimi)
    do
      sh lisa_kasutaja $nimi
    done
  else
    echo "Probleem failiga $failinimi"
  fi
fi

